export const OPTIONS = [
  {
    code: "item1",
    label: "Department of Intercontinental Environmental Sustainability and Resource Management"
  },
  { code: "item2", label: "Ministry of Technological Advancement and Innovation Strategy" },
  { code: "item3", label: "Bureau of National Homeland Security and Resilience Planning" },
  { code: "item4", label: "Office of Rural Economic Development and Agricultural Affairs" },
  { code: "item5", label: "Commission for Urban Infrastructure and Transportation Coordination" },
  { code: "item6", label: "Division of Cultural Heritage Preservation and Arts Promotion" },
  { code: "item7", label: "Agency for Space Exploration and Planetary Research Oversight" },
  { code: "item8", label: "Directorate of Cybersecurity and Information Privacy Assurance" },
  { code: "item9", label: "Council for International Trade Relations and Economic Development" },
  { code: "item10", label: "Institute for Health and Wellness Policy and Regulation" },
  { code: "item11", label: "Secretariat for Biodiversity Conservation and Natural Resources" },
  { code: "item12", label: "Center for Climate Change Mitigation and Adaptation Strategy" },
  { code: "item13", label: "Office of Humanitarian Aid and Disaster Response Coordination" },
  { code: "item14", label: "Bureau of Energy Efficiency and Sustainable Power Generation" },
  { code: "item15", label: "Ministry of Education, Science, and Technological Advancement" },
  { code: "item16", label: "National Commission for Historical Landmark Preservation" },
  { code: "item17", label: "Department of Maritime Security and Oceanic Resource Management" },
  { code: "item18", label: "Agency for Space Exploration and Cosmic Research Oversight" },
  { code: "item19", label: "Division of Public Health and Epidemic Preparedness" },
  { code: "item20", label: "Council for Cultural Diversity and Inclusivity Promotion" },
  { code: "item21", label: "Office of Industrial Regulation and Consumer Protection Oversight" },
  { code: "item22", label: "Bureau of Economic Development and Trade Relations Coordination" },
  { code: "item23", label: "Department of Agricultural Sustainability and Rural Affairs" },
  { code: "item24", label: "Commission for Environmental Conservation and Ecosystem Management" },
  { code: "item25", label: "Ministry of Urban Planning and Metropolitan Development" },
  { code: "item26", label: "Institute for Scientific Research and Technological Advancement" },
  { code: "item27", label: "Secretariat for National Security and Intelligence Strategy" },
  { code: "item28", label: "Directorate of Aerospace Technology and Space Exploration" },
  { code: "item29", label: "Council for International Relations and Diplomatic Affairs" },
  { code: "item30", label: "Division of Wildlife Conservation and Habitat Preservation" },
  { code: "item31", label: "Agency for Healthcare Quality Assurance and Patient Safety" },
  { code: "item32", label: "Center for Renewable Energy and Sustainable Infrastructure" },
  { code: "item33", label: "Office of Emergency Preparedness and Disaster Response" },
  { code: "item34", label: "National Commission for Cultural Heritage Preservation" },
  { code: "item35", label: "Bureau of Oceanography and Marine Resource Management" },
  { code: "item36", label: "Department of Transportation Infrastructure and Public Safety" },
  { code: "item37", label: "Ministry of Public Education and Academic Excellence" },
  { code: "item38", label: "Commission for Historical Preservation and Heritage Restoration" },
  { code: "item39", label: "Institute for Climate Change Research and Mitigation" },
  { code: "item40", label: "Secretariat for Information Technology and Cybersecurity" },
  { code: "item41", label: "Directorate of National Parks and Natural Resources" },
  { code: "item42", label: "Council for International Trade and Economic Development" },
  { code: "item43", label: "Division of Public Health and Pandemic Response" },
  { code: "item44", label: "Agency for Environmental Sustainability and Conservation" },
  { code: "item45", label: "Center for Space Exploration and Cosmic Research" },
  { code: "item46", label: "Office of Urban Development and Infrastructure Planning" },
  { code: "item47", label: "Bureau of Energy Efficiency and Green Technology" },
  { code: "item48", label: "Department of Scientific Innovation and Technological Advancement" },
  { code: "item49", label: "Ministry of Homeland Security and Resilience Strategy" },
  { code: "item50", label: "Commission for Rural Economic Development and Agricultural Policy" },
  { code: "item51", label: "Institute for Cultural Diversity and Inclusivity Promotion" },
  { code: "item52", label: "Secretariat for Disaster Resilience and Humanitarian Aid" },
  { code: "item53", label: "Directorate of Space Technology and Planetary Exploration" },
  { code: "item54", label: "Council for Indigenous Affairs and Community Development" },
  { code: "item55", label: "Division of Coastal Protection and Marine Conservation" },
  { code: "item56", label: "Agency for Healthcare Accessibility and Patient Advocacy" },
  { code: "item57", label: "Center for Sustainable Agriculture and Rural Empowerment" },
  { code: "item58", label: "Office of Environmental Impact Assessment and Monitoring" },
  { code: "item59", label: "Bureau of Trade and Economic Relations Coordination" },
  { code: "item60", label: "Department of Technological Innovation and Research" },
  { code: "item61", label: "Ministry of Historical Preservation and Heritage Conservation" },
  { code: "item62", label: "Commission for Climate Change Adaptation and Mitigation" },
  { code: "item63", label: "Institute for Information Security and Data Privacy" },
  { code: "item64", label: "Secretariat for National Security and Intelligence Oversight" },
  { code: "item65", label: "Directorate of Space Research and Cosmic Exploration" }
]
